//CurrentWorkout Modals
export const SET_IS_FIRST_TIME_LOGIN = "SET_IS_FIRST_TIME_LOGIN";
export const SET_ADD_WEIGHT_MODAL_VISIBILITY =
  "SET_ADD_WEIGHT_MODAL_VISIBILITY";
export const SET_EDIT_WEIGHT_REPS_MODAL_VISIBILITY =
  "SET_EDIT_WEIGHT_REPS_MODAL_VISIBILITY";
