//CurrentWorkout Modals
export const SET_EXERCISE_VISIBILITY = "SET_EXERCISE_VISIBILITY";
export const SET_ADD_WEIGHT_MODAL_VISIBILITY =
  "SET_ADD_WEIGHT_MODAL_VISIBILITY";
export const SET_EDIT_WEIGHT_REPS_MODAL_VISIBILITY =
  "SET_EDIT_WEIGHT_REPS_MODAL_VISIBILITY";
